name: Reference Build

on:
  push:
    branches:
      - "main"
    paths:
      - "lib/**"

jobs:
  reference-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true
    - name: Update md file
      run: bundle exec rake reference
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update reference
        file_pattern: REFERENCE.md
